### PR TITLE
add package: pandoc-citeproc-preamble

### PR DESCRIPTION
**Pull request by huan**
See: #1

### CODE REVIEW

**Comment by thomasWeise** [comment]
I am very sorry, I saw your messages just now ... at least I don't remember seeing it before :-(
Sorry for the delay!
I just merged your request into the repository.

I don't remember seeing #1 either... ...and I also don't remember why I added and removed the package ... 
... so let's just see if the new Dockerfile compiles and if my packages still work afterwards ^_^
In a few hours, we know whether the new Dockerfile works with docker-hub.

**Comment by huan** [comment]
Thank you for come back to my PR, and thanks for merging it.

And it seems worked(from docker hub):
```
Success | latest | 9087cb7 | 20 hours ago | 18 hours ago
```

Would you like someone to maintain this repo with you together? If you like, I would like be a volunteer because I'm a 1st year PhD student and I'm preparing to write my first paper... :-p

**Comment by thomasWeise** [comment]
Hi.
Again, sorry for the delay.
Yes, indeed, the merge seems to work.
I was somewhat concerned because it needs a long time on dockerhub to compile, I think we are close to the point where the build will be aborted.
But for now it works, so that's good.

Regarding the joint managing:
Currently, this container is a part of a larger project of mine.
I created an automated tool chain which can convert books written in markdown to several different formats, details are discussed in https://github.com/thomasWeise/bookbuildeR.
In summary, I made an R package with additional commands extending the markdown syntax to allow hierarchical documents.
The R package is in a docker container "two levels" after this one here.
With that container, I can write an electronic book on github and have it automatically compiled and published after each commit.
That package, the containers, and my book are still in a relatively early stage.
At this point, I may need to change things, e.g., dissect containers if necessary.
Hence, I would like to still hold the complete control about all changes, because otherwise, I might lose track of what happens and if something fails some levels after this container, I won't know why.

However, I very very much value your input.
For now, if you are interested, just directly email me with any issue or suggestion to tweise@hfuu.edu.cn and tweise@ustc.edu.cn.
This way, I won't overlook it like the present issue.

Thank you again, and let's keep in touch.
Thomas.

**Comment by huan** [comment]
@thomasWeise No problem, I fully understand your situation and I'll email you if you do not response on GitHub in the future.

I know that you are in China, so if you have any chance to be in Beijing, please let me know, and I'm happy to have coffee with you near WuDaoKou or Zhongguancun in Haidian.

My email is zixia@zixia.net and my wechat is 918999, let's keep in touch, and have a nice day!

**Pull request merged**
